---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        stages: [commit]
      - id: check-case-conflict
        stages: [commit]
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-shebang-scripts-are-executable
        stages: [commit]
      - id: check-symlinks
        stages: [commit]
      - id: destroyed-symlinks
        stages: [commit]

      - id: check-json
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: check-toml
        stages: [commit]

      - id: check-merge-conflict
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: mixed-line-ending
        stages: [commit]
        args: [--fix=lf]
      - id: trailing-whitespace
        stages: [commit]

      - id: name-tests-test
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        stages: [commit]
        files: \.(md|yml|yaml|json)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        stages: [commit]
        # args: [--ignore-words=.codespellignore]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.16.0
    hooks:
      - id: gitlint

  - repo: local
    hooks:
      - id: format
        name: Format code
        description: Format code
        stages: [commit]
        entry: bash -c '[[ "$CI" != "true" ]] && make format || true'
        language: system
        pass_filenames: false
        always_run: true
