version: "3.9"

services:
  earhorn:
    build:
      context: .
      target: dev
    user: 1000:1000
    volumes:
      - .:/src

  s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/s3:/data:rw

  icecast:
    image: libretime/icecast:latest
    ports:
      - 8000:8000

  liquidsoap:
    image: savonet/liquidsoap:v2.2.1
    command:
      - >
        output.icecast(
          host="icecast",
          mount="/main.ogg",
          %vorbis,
          noise()
        )
    depends_on:
      - icecast
