version: "3.9"

services:
  s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - s3_data:/data:rw

volumes:
  s3_data:
