version: "3.9"

services:
  earhorn:
    image: docker.io/jooola/earhorn:latest
    restart: unless-stopped
    ports:
      - 9950:9950
    volumes:
      - ./data/app:/app
      - ./data/archive:/archive
    env_file:
      - .env
